### ISSUE TITLE
votemanager.py bug, admins passing/veoting the votes.

### ISSUE THREAD

**Issue by Melodeiro** [tjone270/Quake-Live#16]
It looks like, that most of the time there is no vote_ended events. Do you have any idea why, btw? This way self.has_voted is sometimes not cleaned up. Maybe its better to clean it at the start of the vote_started event?

**Comment by tjone270** [comment]
I agree.

**Comment by tjone270** [comment]
Commit ef4d698 fixed this.
> It looks like, that most of the time there is no vote_ended events. Do you have any idea why, btw?

No idea sorry.
