### ISSUE TITLE
votestats.py bug, admins are not showing when they are voted.

### ISSUE THREAD

**Issue by Melodeiro** [tjone270/Quake-Live#17]
If you have admin rights set in the access.txt file, your votes will not be displayed in the chat, just the vote counter will be increased. Also there is a bug, when someone else votes after you, counter remains the same, you don't hear the "pin" sound and only notice the chat message "player voted Yes." Is it even possible to fix, or thats the game restrictions?

**Comment by tjone270** [comment]
Commit 3460cee fixed this:
> Also there is a bug, when someone else votes after you, counter remains the same, you don't hear the "pin" sound and only notice the chat message "player voted Yes." Is it even possible to fix, or thats the game restrictions?

This sounds like default admin behaviour from my `votemanager.py` plugin:
> If you have admin rights set in the access.txt file, your votes will not be displayed in the chat, just the vote counter will be increased.
