### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by jeromim** [tjone270/Quake-Live#5]
hello, a suggestion !info.py. When I type !info 2 appears (IP) and (NICK), you could implement to (IP), (NICK - steamid) or a way of informing accounts with two STEAM. To discover the fakes

**Comment by tjone270** [comment]
Good idea, will try to do that in the future, thanks :D

**Comment by tjone270** [comment]
I'll leave the issue open until I make the appropriate change.

**Comment by jeromim** [comment]
okay, and I thank you for all you have done for the community QuakeLive

**Comment by tjone270** [comment]
The `aliases.py` plugin now supports IP scanning as well as name listing.
